import FSCProbes.UniversalAnalyticAdverses

#check FSCProbes.UniversalAnalyticAdverses.triangle_universal_derivative
#check FSCProbes.UniversalAnalyticAdverses.fiveGram_actual_peano
#check FSCProbes.UniversalAnalyticAdverses.fiveGram_actual_variation
#check FSCProbes.UniversalAnalyticAdverses.antipodal_zero_not_differentiable
#print axioms FSCProbes.UniversalAnalyticAdverses.triangle_trace_coefficient
#print axioms FSCProbes.UniversalAnalyticAdverses.triangle_universal_derivative
#print axioms FSCProbes.UniversalAnalyticAdverses.fiveGram_rank_le_two
#print axioms FSCProbes.UniversalAnalyticAdverses.fiveGram_isCorrelation
#print axioms FSCProbes.UniversalAnalyticAdverses.fiveGram_distinct
#print axioms FSCProbes.UniversalAnalyticAdverses.fiveGram_actual_law
#print axioms FSCProbes.UniversalAnalyticAdverses.fiveGram_actual_peano
#print axioms FSCProbes.UniversalAnalyticAdverses.fiveGram_actual_variation
#print axioms FSCProbes.UniversalAnalyticAdverses.duplicate_scores_excluded
#print axioms FSCProbes.UniversalAnalyticAdverses.duplicate_support_not_differentiable
#print axioms FSCProbes.UniversalAnalyticAdverses.antipodal_zero_not_differentiable
